---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: dq-mysql-client
  name: dq-mysql-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dq-mysql-client
    spec:
      containers:
      - image: quay.io/ukhomeofficedigital/phpmyadmin:latest
        name: dq-mysql-client
        imagePullPolicy: Always
        ports:
          - containerPort: 5055
        resources:
          limits:
            memory: "1Gi"
            cpu: "800m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
      restartPolicy: Always
